import React from 'react';
import { Breadcrumbs } from '@/components/layout/Breadcrumbs';
import { BRAND_CONFIG } from '@/config/brand';
import { constructMetadata } from '@/lib/seo';

export const metadata = constructMetadata({
  title: `Disclaimer — ${BRAND_CONFIG.name}`,
  description: `General disclaimer regarding calculation outputs and utility results on ${BRAND_CONFIG.name}.`,
});

export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      <Breadcrumbs items={[{ label: 'Disclaimer' }]} />

      <div className="space-y-4">
        <h1 className="font-heading font-extrabold text-3xl md:text-4xl text-slate-900 dark:text-slate-100 tracking-tight">
          Disclaimer
        </h1>
        <p className="text-xs font-semibold text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-950/50 px-4 py-2 rounded-xl border border-amber-200 dark:border-amber-800 w-fit">
          Note: Development Copy — Subject to final review prior to production release.
        </p>
      </div>

      <div className="prose dark:prose-invert max-w-none space-y-6 text-slate-600 dark:text-slate-300 text-sm md:text-base leading-relaxed">
        <h2 className="font-heading text-xl font-bold text-slate-900 dark:text-slate-100">Calculation & Financial Output</h2>
        <p>
          Calculations generated by financial tools (such as EMI Calculator, GST Calculator, and SIP Calculator) are intended solely for educational and estimation purposes. They do not constitute official financial advice or guarantees from financial institutions.
        </p>

        <h2 className="font-heading text-xl font-bold text-slate-900 dark:text-slate-100">Academic Conversion Rules</h2>
        <p>
          Educational tools (such as CGPA and Attendance Calculators) utilize standard formula assumptions. Different universities or institutions may enforce unique conversion policies.
        </p>
      </div>
    </div>
  );
}
